#!/usr/bin/env node
/* eslint-disable no-console, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports */
/**
 * Icon Barrel Generator
 *
 * Scans assets/icons/ for SVG files and generates a typed barrel export
 * at assets/icons/index.ts.
 *
 * Usage:
 *   node scripts/generate-icons.js
 *   pnpm icons
 *
 * Workflow:
 *   1. Download an SVG from https://www.streamlinehq.com/
 *   2. Drop it into assets/icons/
 *   3. Run this script
 *   4. Use <AppIcon name="YourIcon" /> in your component
 */

const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.resolve(__dirname, '../assets/icons');
const OUTPUT_FILE = path.join(ICONS_DIR, 'index.ts');

function toPascalCase(filename) {
  return filename
    .replace(/\.svg$/i, '')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

function generate() {
  const files = fs
    .readdirSync(ICONS_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));

  if (files.length === 0) {
    const content = [
      '// Auto-generated by scripts/generate-icons.js — do not edit manually',
      '// Add SVG files to assets/icons/ and run: pnpm icons',
      '',
      "import type { SvgProps } from 'react-native-svg';",
      '',
      'export const Icons: Record<string, React.FC<SvgProps>> = {};',
      '',
    ].join('\n');

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log('No SVG files found. Generated empty Icons map.');
    return;
  }

  const seen = new Map();
  const entries = [];

  for (const file of files) {
    let name = toPascalCase(file);

    if (seen.has(name)) {
      const count = seen.get(name) + 1;
      seen.set(name, count);
      name = `${name}${count}`;
    } else {
      seen.set(name, 1);
    }

    entries.push({ name, file });
  }

  const imports = entries.map(({ name, file }) => `import ${name} from './${file}';`).join('\n');

  const exports = entries.map(({ name }) => `  ${name},`).join('\n');

  const content = [
    '// Auto-generated by scripts/generate-icons.js — do not edit manually',
    '// Add SVG files to assets/icons/ and run: pnpm icons',
    '',
    imports,
    '',
    'export const Icons = {',
    exports,
    '} as const;',
    '',
  ].join('\n');

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`Generated ${entries.length} icon(s) in assets/icons/index.ts`);
}

generate();
