// Auto-generated by scripts/generate-icons.js — do not edit manually
// Add SVG files to assets/icons/ and run: pnpm icons

import AiFileSpark from './Ai-File-Spark.svg';
import CalendarEvent from './Calendar-Event.svg';
import EntEarNoseThroat from './Ent-Ear-Nose-Throat.svg';
import Medicines from './Medicines.svg';
import Stethoscope from './Stethoscope.svg';

export const Icons = {
  AiFileSpark,
  CalendarEvent,
  EntEarNoseThroat,
  Medicines,
  Stethoscope,
} as const;
